# -*- mode: ruby -*-

Vagrant.configure('2') do |config|
  config.vm.box = 'precise64'
  config.vm.box_url = 'http://files.vagrantup.com/precise64.box'

  config.vm.provider :virtualbox do |v|
    v.customize ['modifyvm', :id, '--name', 'messaging-part-1']
    v.customize ['modifyvm', :id, '--memory', 1024]
  end

  config.vm.hostname = 'messaging-part-1'

  config.vm.network :private_network, ip: '1.2.3.4'

  config.vm.synced_folder '..', '/home/vagrant/abstract-internal-messaging'
  config.vm.synced_folder 'salt/roots', '/srv'

  config.vm.provision :salt do |salt|
    salt.minion_config = 'salt/minion.conf'
    salt.run_highstate = true
    salt.verbose = true
  end
end
